title: Madison Hansen
description: > # this means to ignore newlines until "baseurl:"
  Madison Hansen is a Math Tutor & ESL Instructor based in Washington, DC.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hansen-teaching.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: "https://twitter.com/rhiannon_io" #if your site has a twitter account, enter it here

# Author Settings
author: Madison Hansen # add your name
author-img: Madison Hansen - Author Photo.png # add your photo
about-author: a Math Tutor & ESL Instructor based in Washington, DC. I have 11 years of experience in tutoring, teaching, data science, and biology research.  I am also passionate about music, dance, and international travel. # add description
social-twitter: rhiannon_io # add your Twitter handle
social-facebook: rhiannonmarypayne # add your Facebook handle
social-github: rhiannon-io # ig handle
social-linkedin: rhipayne # add your Linkedin handle
social-email: payne@rhiannon.io # add your Email address

Disqus
discus-identifier: Rhiannon Payne # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
